# fly.toml app configuration file generated for memgpt-server-app-twilight-sun-3767 on 2024-06-27T11:44:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "memgpt-server-app-twilight-sun-3767"
primary_region = "cdg"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8083
min_machines_running = 0
processes = [ "app" ]
   [http_service.http_options.response.headers]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "*"
      Access-Control-Allow-Headers = "*"

[mounts]
source = "u_data"
destination = "/data"

[[vm]]
cpu_kind = "performance"
cpus = 1
memory = "2gb"
