[defaults]
preset = memgpt_chat
persona = u
human = basic

[model]
model = gpt-4o
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
model_wrapper = null
context_window = 8192

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-3-large
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /root/.memgpt/chroma
uri = null

[recall_storage]
type = sqlite
path = /root/.memgpt
uri = null

[metadata_storage]
type = sqlite
path = /root/.memgpt
uri = null

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000