[defaults]
preset = u-preset
persona = u
human = default

[model]
model = gpt-4o
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
model_wrapper = null
context_window = 127000

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-3-large
embedding_dim = 3072
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /data/chroma
uri = null

[recall_storage]
type = sqlite
path = /data
uri = null

[metadata_storage]
type = sqlite
path = /data
uri = null

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000